name: Build APK (Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      SHORTLINK: ${{ secrets.SHORTLINK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make entrypoint executable for this run
        run: |
          if [ -f ./entrypoint.sh ]; then
            chmod +x ./entrypoint.sh || true
          fi
          if [ -d ./scripts ]; then
            find ./scripts -type f -name "*.sh" -exec chmod +x {} \; || true
          fi
          echo "权限 gesetzt (falls vorhanden):"
          ls -la entrypoint.sh || true
          ls -la scripts || true

      - name: Build Docker image
        run: docker build -t baserow-buildozer .

      - name: Build APK (containerized)
        run: docker run --rm -v "${{ github.workspace }}":/home/builduser/app -e SHORTLINK="${{ secrets.SHORTLINK }}" baserow-buildozer

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: baserow-app-apk
          path: ./.buildozer/android/platform/build-*/dists/*/bin/*.apk
