name: Build APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo auschecken
      - name: Repository auschecken
        uses: actions/checkout@v3

      # 2️⃣ APK bauen mit Docker (in einer Zeile, non-root, Container-intern)
      - name: APK bauen mit Docker
        run: docker run --rm -v $PWD:/app:ro -w /home/user -e SHORTLINK=${{ secrets.SHORTLINK }} ghcr.io/kivy/buildozer:latest /bin/bash -c "mkdir -p buildozer_src && cp -r /app/* buildozer_src && cd buildozer_src && buildozer android debug && cp bin/*.apk /app/bin/"

      # 3️⃣ APK hochladen
      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: baserowapp-apk
          path: bin/*.apk
