name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      SHORTLINK: ${{ secrets.SHORTLINK }}

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Ausführbare Dateien erzwingen
      - name: Set Executable Permissions
        run: |
          # Beispiel: falls du entrypoint.sh oder andere Skripte hast
          chmod +x ./entrypoint.sh
          # Optional alle .sh in scripts/:
          if [ -d ./scripts ]; then chmod +x ./scripts/*.sh; fi
          # Prüfen:
          ls -l ./entrypoint.sh
          if [ -d ./scripts ]; then ls -l ./scripts; fi

      # 3️⃣ Docker Image bauen
      - name: Build Docker Image
        run: |
          docker build -t baserow-buildozer .

      # 4️⃣ APK bauen mit Docker
      - name: Build APK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/builduser/app \
            -w /home/builduser/app \
            -e SHORTLINK="${SHORTLINK}" \
            baserow-buildozer \
            /bin/bash -c "buildozer android debug"

      # 5️⃣ APK als Artifact hochladen
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: baserow-app-apk
          path: ./.buildozer/android/platform/build-arm64-v8a/dists/BaserowApp/bin/*.apk
