name: Build APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo auschecken
      - name: Repository auschecken
        uses: actions/checkout@v3

      # 2️⃣ Docker Buildozer Container nutzen
      - name: APK bauen mit Docker
        run: |
          docker run --rm -v $PWD:/app -w /app --user $(id -u):$(id -g) ghcr.io/kivy/buildozer:latest buildozer android debug

      # 3️⃣ APK hochladen
      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: baserowapp-apk
          path: bin/*.apk
