name: Build APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Docker Container starten und APK bauen
        run: |
          docker run --rm -v $PWD:/app -w /app \
          ghcr.io/kivy/buildozer:latest \
          /bin/bash -c "buildozer android debug"
