name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython kivy requests python-dotenv

      - name: Buildozer vorbereiten
        run: |
          buildozer init
          # Optional: buildozer.spec anpassen, falls nicht im Repo

      - name: APK bauen
        run: |
          buildozer android debug

      - name: APK hochladen
        uses: actions/upload-artifact@v3
        with:
          name: baserowapp-apk
          path: bin/*.apk
