name: Build APK (Custom Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo auschecken
      - name: Repository auschecken
        uses: actions/checkout@v3

      # 2️⃣ Docker-Image bauen
      - name: Docker Image bauen
        run: docker build -t baserow-buildozer .

      # 3️⃣ APK bauen im Container
      - name: Build APK
        run: ddocker run --rm -v ${{ github.workspace }}:/home/builduser/app -w /home/builduser/app --user $(id -u):$(id -g) -e SHORTLINK=${{ secrets.SHORTLINK }} baserow-buildozer /bin/bash -c ". .venv/bin/activate && buildozer android debug"

      # 4️⃣ APK hochladen
      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: baserowapp-apk
          path: bin/*.apk
