name: Build APK (Docker image)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      SHORTLINK: ${{ secrets.SHORTLINK }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t baserow-buildozer .

     - name: Build APK (containerized)
       run: docker run --rm -v ${{ github.workspace }}:/home/builduser/app -e SHORTLINK="${SHORTLINK}" baserow-buildozer


      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: baserow-app-apk
          # Pfad ggf. anpassen, falls Buildozer andere arch/naming nutzt
          path: ./.buildozer/android/platform/build-arm64-v8a/dists/*/bin/*.apk
