name: Build APK (Docker, Stable)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Repository auschecken
        uses: actions/checkout@v3

      # 2️⃣ APK bauen in Container-internem Verzeichnis (non-interaktiv, root erlaubt)
      - name: APK bauen mit Docker
        run: docker run --rm -v $PWD:/app:ro -w /home/user -e SHORTLINK=${{ secrets.SHORTLINK }} -e BUILDOZER_ALLOW_ROOT=1 ghcr.io/kivy/buildozer:latest /bin/bash -c "mkdir -p buildozer_src && cp -r /app/* buildozer_src && cd buildozer_src && buildozer android debug && mkdir -p /app/bin && cp bin/*.apk /app/bin/"

      # 3️⃣ APK hochladen als Artifact
      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: baserowapp-apk
          path: bin/*.apk
