name: Build APK (Custom Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SHORTLINK: ${{ secrets.SHORTLINK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo auschecken
      - name: Repository auschecken
        uses: actions/checkout@v3

      # 2️⃣ Docker-Image bauen
      - name: Docker Image bauen
        run: docker build -t baserow-buildozer .

      # 3️⃣ APK bauen im Container
      - name: APK bauen
        run: docker run --rm -w /home/builduser/app -e SHORTLINK=${{ secrets.SHORTLINK }} baserow-buildozer /bin/bash -c "mkdir -p /home/builduser/app && cd /home/builduser/app && cp -r /host_app/* . && buildozer android debug"



      # 4️⃣ APK hochladen
      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: baserowapp-apk
          path: bin/*.apk
